name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pyqt5-dev-tools xvfb

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install tox
        run: pip install tox

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: tox -- --forked --verbose